### ISSUE TITLE
Decimal problem

### ISSUE THREAD

**Issue by 157946a** [Andre601/Math-Expansion#1]
The reason is this, I use version 1.2.0, and then I write %math_{server_time_s}[precision:0]%, and then display the overall variables instead of outputting the current number of seconds on the server. Request a quick fix.

**Comment by Andre601** [comment]
The math expansion changed in syntax, which was explained in the readme, the changelog.md and the release on the ecloud

**Comment by 157946a** [comment]
I received it. I didn’t pay attention to the ecloud remarks when I downloaded it. I downloaded it with instructions
