### ISSUE TITLE
Error when using 0 decimal places

### ISSUE THREAD

**Issue by 157946a** [Andre601/Math-Expansion#14]
### I confirm that...

- [X] I use the latest version of the expansion. [[Expansion Page](https://api.extendedclip.com/expansions/math/) | [Changelog](https://github.com/Andre601/Math-Expansion/blob/master/CHANGELOG.md)]
- [X] The issue is not caused by PlaceholderAPI or any other plugin or expansion
- [X] Any used placeholder works as intendet (`/papi parse me <placeholders>`)

### Description

I have a problem. When I use the calculation, if the decimal place is 0, it will be invalid. For example, if I use %math_0_{vault_eco_balance}/999-0.5%, then my current balance is 1048, It will appear -0.549049049049049049049049049049049049049049049049049049049049049049049049049049049049049049049049049049049049049049049049049049, and using %math_1_{vault_eco_balance}/999-0.5% will return to the normal 0.5, using %math_0_{vault_eco_balance}/999-0.5% The result should be 1

### Logs

```text
null
```

### Math Expansion version

```text
[20:21:32 INFO]: Rueske issued server command: /papi parse me %math_0_{vault_eco_balance}/999-0.5%
```

### PlaceholderAPI version

```text
[20:31:29 INFO]: PlaceholderAPI version 2.11.1
[20:31:29 INFO]: An awesome placeholder provider!
[20:31:29 INFO]: Author: HelpChat
```

### Server version

```text
[20:31:46 INFO]: This server is running Paper version git-Paper-1618 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
```

**Comment by Andre601** [comment]
Try `%math_0:_{vault_eco_balance}/999-0.5%`

**Comment by 157946a** [comment]
Same

**Comment by Andre601** [comment]
I can't really help you with that. Pretty sure that's a unfortunate behaviour of either EvalEx or BigDecimal from Java

**Comment by Andre601** [comment]
After looking at bit closer, it's a Java issue.

Javadocs from [`BigDecimal#round(MathContex)`](https://docs.oracle.com/javase/9/docs/api/java/math/BigDecimal.html#round-java.math.MathContext-) which is used here:
> Returns a BigDecimal rounded according to the MathContext settings. **If the precision setting is 0 then no rounding takes place.**

**Comment by 157946a** [comment]
In addition to reducing the version, is there any way to not display decimals (except js)

**Comment by Andre601** [comment]
Just want to inform that I pushed a release a while back that fixed an annoying issue with how numbers are displayed.
Perhaps this fixed your issue too?
