### ISSUE TITLE
can't set precision

### ISSUE THREAD

**Issue by alan67160** [Andre601/Math-Expansion#3]
![image](https://user-images.githubusercontent.com/20385640/126063608-5365da95-700b-4f0c-8139-d00d59fe60fe.png)
I have tried %math_1:_5.6+4.77%, %math_1:up_5.6+4.77%, %math_0:up_5.6+4.77% and notthing work

**Comment by Andre601** [comment]
You got it fixed?
Also, why censor parts of the placeholder?

**Comment by Baterka** [comment]
I have same problem

**Comment by Andre601** [comment]
Helps me not at all

**Comment by alan67160** [comment]
@Andre601 @Baterka delete and redownload from eclord
