### ISSUE TITLE
`110,000/100` returns invalid placeholder

### ISSUE THREAD

**Issue by watchmebejammy** [Andre601/Math-Expansion#7]
25.01 19:52:39 [Server] WARN [PlaceholderAPI] [Math] Invalid Placeholder detected!
25.01 19:52:39 [Server] WARN [PlaceholderAPI] [Math] Placeholder: %math_{prison_rankup_cost_default}*0.01%
25.01 19:52:39 [Server] WARN [PlaceholderAPI] [Math] '110,000*0.01' is not a valid Math Expression.

As you can see I've done different calculations, and both the same outcome.

25.01 19:47:38 [Server] WARN [PlaceholderAPI] [Math] Invalid Placeholder detected!
25.01 19:47:38 [Server] WARN [PlaceholderAPI] [Math] Placeholder: %math_{prison_rankup_cost_default}/100%
25.01 19:47:38 [Server] WARN [PlaceholderAPI] [Math] '110,000/100' is not a valid Math Expression.

Any help is greatly appreciated, thank you!

**Comment by watchmebejammy** [comment]
apologies for the bad formatting with the **

**Comment by watchmebejammy** [comment]
![image](https://user-images.githubusercontent.com/98424543/151049706-e8c6280c-4094-499c-8c25-17d12470622e.png)

**Comment by Andre601** [comment]
My personal guess is, that `,` isn't supported for the math calculations.

**Comment by watchmebejammy** [comment]
oh Im an idiot I should be using a raw number placeholder, I'll try that now thank you!

**Comment by Andre601** [comment]
Did this work? If so I'll close this issue now.

**Comment by Andre601** [comment]
I'll close this issue since I haven't received any response.
If the issue still exists, let me know so that I can re-open it.
