### ISSUE TITLE
Problems with placeholders in math, using curly brackets

### ISSUE THREAD

**Issue by Broken-Anvil** [Andre601/Math-Expansion#9]
### I confirm that...

- [x] I use the latest version of the expansion. [[Expansion Page](https://api.extendedclip.com/expansions/math/) | [Changelog](https://github.com/Andre601/Math-Expansion/blob/master/CHANGELOG.md)]
- [X] The issue is not caused by PlaceholderAPI or any other plugin or expansion
- [X] Any used placeholder works as intendet (`/papi parse me <placeholders>`)

### Description

So I understand how to use this math expansion. Especially the feature of placeholders in math is a big win.

To use placeholders in math, you should replace the `%placeholder%` with `{placeholder}`, and add an operator, like:
`%math_{server_online}-1%`

Now the problem comes, where the used placeholders, use curly brackets in them, using the Scoreboard Objective Placeholder, an extension for Placeholder API, from cj89898 (link below). This extension uses curly brackets for the scoreboard objective and player, for example:
`%objective_score_{balance}_{username}%`

And in the math program, it will look like this:
`%math_{objective_score_{balance}_{username}}-1%`

But that isn't working, since the math expansions recognize the curly brackets in the objective placeholder as "end" for the whole placeholder, resulting in an error. For example, I have a scoreboard objective, called "balance", and me (Broken_Anvil) has 50 balance. I want to subtract one balance from that. That would be:
`%math_{objective_score_{balance}_{Broken_Anvil}-1%` (should give a value of 49)

Returns an error, or incomplete placeholder, shown:
`%math_{objective_score_{balance}_{Broken_Anvil}-1%`

It simply doesn't process the placeholder. Is there a solution for this? Would be really appreciated! Thanks in advance.

### Logs

```text
Input:
 %math_{objective_score_{balance}_{Broken_Anvil}-1%

Output:
 %math_{objective_score_{balance}_{Broken_Anvil}-1%

Expected:
 49

Input:
 %objective_score_{balance}_{Broken_Anvil}%

Output:
 50

Expected:
 50

```

### Math Expansion version

```text
Placeholder expansion info for: math
Status: Registered
Author: Andre_601
Version: 1.3.2
```

### PlaceholderAPI version

```text
PlaceholderAPI version 2.11.1
An awesome placeholder provider!
Author: HelpChat
```

### Server version

```text
This server is running Paper version git-Paper-18 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT)
```

**Comment by Andre601** [comment]
Hey there!

This is unfortunately a downside of how PlaceholderAPI is handling placeholders and nothing I can fix on my end.
A possible workaround would be to use the [Shortcut Expansion](https://api.extendedclip.com/expansions/shortcut/). With it could you create a TXT file containing the placeholder like this:

```
%objective_score_{balance}_{username}%
```

...then could you use `{shortcut_<file>}` inside the math placeholder (replace `<file>` with the file name you chose WITHOUT the `.txt` ending).

Example:
```
%math_{shortcut_example}-1%
```

That's currently the only way to bypass this issue and it also isn't a perfect solution, but for what it is does it work.

**Comment by Broken-Anvil** [comment]
Thank you so much for suggesting Shortcut Expansion to me, Andre601!

This solved my problem. It works perfectly fine now.

Big thank you!
